version: '3.8'

services:
  app:
    image: borheneddinebenattia/foyerdevopsbackend
    build:
      context: .
    ports:
      - "8085:8085"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://db:3306/db?createDatabaseIfNotExist=true
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: 0000
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
    depends_on:
      - db
  frontend:
    image: borheneddinebenattia/foyerdevopsfront:latest
    ports:
      - "4200:80"
  db:
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_DATABASE: db
      MYSQL_ROOT_PASSWORD: 0000
    ports:
      - "3306:3306"
